module.exports = {
  dependencies: [
    'husky',
    'lodash',
    'react',
    'react-dom',
    'react-router-dom',
  ],
  devDependencies: [
    '@types/node',
    '@types/react',
    '@types/react-dom',
    '@types/react-router-dom',
    'husky',
    'tslib',
    'typescript',
    'ts-node',
    'clean-webpack-plugin',
    'css-loader',
    'html-webpack-plugin',
    'mini-css-extract-plugin',
    'node-sass',
    'sass-loader',
    'source-map-loader',
    'style-loader',
    'ts-loader',
    'tslint',
    'tslint-config-prettier',
    'tslint-react',
    'typescript',
    'webpack',
    'webpack-cli',
    'webpack-dev-server',
    'webpack-md5-hash',
  ],
};
